# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-08 15:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20160630_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventplayer',
            name='event',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
        ),
    ]
