# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-26 14:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('handicap', models.IntegerField()),
                ('komi', models.DecimalField(decimal_places=1, max_digits=10)),
                ('result', models.CharField(choices=[(b'black', 'Black Wins'), (b'white', 'White Wins'), (b'draw', 'Draw')], max_length=16)),
                ('win_reason', models.CharField(choices=[(b'points', 'Points'), (b'resignation', 'Resignation'), (b'walkover', 'Walkover')], max_length=16)),
                ('points', models.DecimalField(decimal_places=1, max_digits=10)),
                ('date', models.DateField(db_index=True)),
            ],
            options={
                'verbose_name': 'game',
                'verbose_name_plural': 'games',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='game',
            name='black_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_as_black', to='games.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='white_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_as_white', to='games.Player'),
        ),
    ]
