# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-29 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
