# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-30 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_game_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='unrated',
            field=models.BooleanField(default=False),
        ),
    ]
