# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-30 04:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_auto_20160630_0119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='win_reason',
            new_name='reason',
        ),
    ]
