# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-07 17:03
from __future__ import unicode_literals

import aago_ranking.games.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_auto_20160707_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='points',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10, validators=[aago_ranking.games.models.validate_whole_halfs]),
        ),
    ]
