# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-08 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_auto_20160707_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_aago_member',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
